server_tokens off;
more_clear_headers Server;
more_clear_headers X-Powered-By;
more_clear_headers X-Runtime;
more_clear_headers X-Version;
more_clear_headers X-AspNet-Version;
more_clear_headers X-Generator;
