"""
Multi-Provider LLM Router (`FR-PX-1301` to `FR-PX-1304`).

Provider Abstraction Layer with fallback chains (`NFR-REL-003`), task-class routing (`FR-PX-1302`),
caching (`FR-PX-1303`), and comprehensive cost accounting (`FR-PX-1304`).
"""
import os
import time
import json
import hashlib
import logging
from enum import Enum
from typing import Dict, Any, List, Optional, Union
from pydantic import BaseModel, Field

logger = logging.getLogger("evolutionos.execution.providers.llm.router")


class TaskClass(str, Enum):
    """FR-PX-1302: Task classes mapping to appropriate cost/performance provider tiers."""
    REASONING_HEAVY = "REASONING_HEAVY"        # Complex strategy or deep analysis
    GENERATION_BULK = "GENERATION_BULK"        # Script scene narration or bulk text
    CLASSIFICATION_CHEAP = "CLASSIFICATION_CHEAP"  # Simple sentiment/intent classification


class LLMRequest(BaseModel):
    system_prompt: str
    user_prompt: str
    task_class: TaskClass = TaskClass.GENERATION_BULK
    experiment_id: str = "exp_default"
    cacheable: bool = False
    json_mode: bool = False


class LLMResponse(BaseModel):
    content: str
    provider_used: str
    model_used: str
    tokens_in: int
    tokens_out: int
    cost_usd: float
    cached: bool = False


class CostLedgerEntry(BaseModel):
    """FR-PX-1304: Cost ledger entry tracking spend per request and experiment."""
    request_id: str
    experiment_id: str
    provider: str
    model: str
    task_class: str
    tokens_in: int
    tokens_out: int
    cost_usd: float
    timestamp: float = Field(default_factory=time.time)


class CostLedger:
    """Aggregates LLM request costs across experiments (`FR-PX-1304`)."""
    def __init__(self):
        self.entries: List[CostLedgerEntry] = []

    def log_entry(self, entry: CostLedgerEntry) -> None:
        self.entries.append(entry)
        logger.debug(f"Cost ledger logged: ${entry.cost_usd:.4f} ({entry.provider}/{entry.model}) for [{entry.experiment_id}]")

    def get_experiment_total_cost(self, experiment_id: str) -> float:
        return sum(e.cost_usd for e in self.entries if e.experiment_id == experiment_id)

    def get_total_cost(self) -> float:
        return sum(e.cost_usd for e in self.entries)


class BaseLLMProvider:
    """Abstract provider in the pool (`FR-PX-1301`)."""
    def __init__(self, name: str, model: str, cost_per_1k_in: float, cost_per_1k_out: float):
        self.name = name
        self.model = model
        self.cost_per_1k_in = cost_per_1k_in
        self.cost_per_1k_out = cost_per_1k_out

    def estimate_cost(self, tokens_in: int, tokens_out: int) -> float:
        return round((tokens_in / 1000.0 * self.cost_per_1k_in) + (tokens_out / 1000.0 * self.cost_per_1k_out), 6)

    def generate(self, req: LLMRequest) -> LLMResponse:
        """Simulate or execute generation."""
        # Estimate token counts (~4 chars per token)
        tokens_in = max(10, len(req.system_prompt + req.user_prompt) // 4)
        tokens_out = 150
        cost = self.estimate_cost(tokens_in, tokens_out)

        content = f"[Generated by {self.name}/{self.model} for {req.task_class.value}] Response to: {req.user_prompt[:50]}"
        if req.json_mode:
            content = json.dumps({"status": "success", "provider": self.name, "text": content})

        return LLMResponse(
            content=content,
            provider_used=self.name,
            model_used=self.model,
            tokens_in=tokens_in,
            tokens_out=tokens_out,
            cost_usd=cost,
            cached=False
        )


class MultiProviderLLMRouter:
    """Routes requests by task class, handles fallback chains, caching, and cost logging (`FR-PX-1301 to 1304`)."""

    def __init__(self, ledger: Optional[CostLedger] = None):
        self.ledger = ledger or CostLedger()
        self.cache: Dict[str, LLMResponse] = {}  # FR-PX-1303

        # Provider Pool (`FR-PX-1301`)
        self.providers: Dict[str, BaseLLMProvider] = {
            "groq_reasoning": BaseLLMProvider("Groq", "llama-3.3-70b-versatile", cost_per_1k_in=0.0005, cost_per_1k_out=0.0008),
            "groq_fast": BaseLLMProvider("Groq", "llama-3.1-8b-instant", cost_per_1k_in=0.00005, cost_per_1k_out=0.00008),
            "openai_fallback": BaseLLMProvider("OpenAI", "gpt-4o-mini", cost_per_1k_in=0.00015, cost_per_1k_out=0.0006),
            "local_cheap": BaseLLMProvider("Local", "qwen-2.5-1.5b", cost_per_1k_in=0.0, cost_per_1k_out=0.0)
        }

        # Routing Policy (`FR-PX-1302`): maps TaskClass to ordered fallback chain (`NFR-REL-003`)
        self.routing_table: Dict[TaskClass, List[str]] = {
            TaskClass.REASONING_HEAVY: ["groq_reasoning", "openai_fallback", "local_cheap"],
            TaskClass.GENERATION_BULK: ["groq_fast", "openai_fallback", "local_cheap"],
            TaskClass.CLASSIFICATION_CHEAP: ["local_cheap", "groq_fast", "openai_fallback"]
        }

    def _get_cache_key(self, req: LLMRequest) -> str:
        raw = f"{req.task_class.value}:{req.system_prompt}:{req.user_prompt}:{req.json_mode}"
        return hashlib.sha256(raw.encode("utf-8")).hexdigest()

    def route_and_execute(self, req: LLMRequest) -> LLMResponse:
        """Execute request with caching, task-class routing, fallback chain, and cost accounting."""
        # 1. Check cache (`FR-PX-1303`)
        if req.cacheable:
            cache_key = self._get_cache_key(req)
            if cache_key in self.cache:
                logger.debug("LLM cache hit (`FR-PX-1303`).")
                cached_resp = self.cache[cache_key].model_copy(update={"cached": True})
                return cached_resp

        # 2. Get provider fallback chain for this task class (`FR-PX-1301`, `FR-PX-1302`)
        chain = self.routing_table.get(req.task_class, ["groq_fast", "local_cheap"])
        last_exception = None

        for provider_key in chain:
            provider = self.providers.get(provider_key)
            if not provider:
                continue
            try:
                resp = provider.generate(req)

                # 3. Log to Cost Ledger (`FR-PX-1304`)
                entry = CostLedgerEntry(
                    request_id=f"req_{int(time.time()*1000)}",
                    experiment_id=req.experiment_id,
                    provider=resp.provider_used,
                    model=resp.model_used,
                    task_class=req.task_class.value,
                    tokens_in=resp.tokens_in,
                    tokens_out=resp.tokens_out,
                    cost_usd=resp.cost_usd
                )
                self.ledger.log_entry(entry)

                # 4. Save to cache (`FR-PX-1303`)
                if req.cacheable:
                    cache_key = self._get_cache_key(req)
                    self.cache[cache_key] = resp

                return resp
            except Exception as e:
                logger.warning(f"Provider {provider_key} failed: {e}. Attempting fallback...")
                last_exception = e

        raise RuntimeError(f"All providers failed for {req.task_class.value}. Last error: {last_exception}")
